spring:
  application:
    name: store-account
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://horizontes.c5w4osi0sl7q.us-east-2.rds.amazonaws.com:5432/horizontes}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:tRD5jASTYt4Wq7}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: account
  jpa:
    properties:
      hibernate:
        default_schema: account

management:
  endpoints:
    web:
      base-path: /accounts/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://10.100.110.190:8761/eureka/}

springdoc:
  api-docs:
    path: /accounts/v3/api-docs
  swagger-ui:
    path: /accounts/swagger-ui.html